apiVersion: v1
kind: Service
metadata:
  name: jeevandata-backend
  namespace: jeevandata
  labels:
    app: jeevandata
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: jeevandata
    tier: backend
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: jeevandata-frontend
  namespace: jeevandata
  labels:
    app: jeevandata
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: jeevandata
    tier: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
