'use client';

import { cn } from '@/lib/utils';

interface BriefData {
  summary: string;
  chiefComplaint: string;
  riskFlags: string[];
  vitalsToCheck: string[];
  suggestedFollowups: string[];
  medicationsNote: string;
  icd10Hints: string[];
}

interface BriefCardProps {
  brief: BriefData;
  className?: string;
}

export function BriefCard({ brief, className }: BriefCardProps) {
  return (
    <div
      role="region"
      aria-label="Clinical intake brief"
      className={cn('w-full max-w-2xl space-y-4', className)}
    >
      {/* Header */}
      <div className="flex items-center gap-2">
        <div
          aria-hidden="true"
          className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-100"
        >
          <svg
            className="h-4 w-4 text-emerald-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
            />
          </svg>
        </div>
        <div>
          <h2 className="text-lg font-semibold text-slate-900">Clinical Intake Brief</h2>
          <p className="text-xs text-slate-500">
            Generated by Jeevandata AI &middot; Ready for doctor review
          </p>
        </div>
      </div>

      {/* Brief Card */}
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        {/* Summary */}
        <div className="border-b border-slate-100 p-5">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Summary
          </h3>
          <p className="text-sm leading-relaxed text-slate-700">{brief.summary}</p>
        </div>

        {/* Chief Complaint */}
        <div className="border-b border-slate-100 p-5">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Chief Complaint
          </h3>
          <p className="text-base font-medium text-slate-900">{brief.chiefComplaint}</p>
        </div>

        {/* Risk Flags */}
        {brief.riskFlags.length > 0 && (
          <div className="border-b border-slate-100 p-5">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-red-500">
              Risk Flags
            </h3>
            <div className="flex flex-wrap gap-2">
              {brief.riskFlags.map((flag) => (
                <span
                  key={flag}
                  className="inline-flex items-center rounded-full bg-red-50 px-3 py-1 text-xs font-medium text-red-700 ring-1 ring-red-200"
                >
                  <span aria-hidden="true" className="mr-1">
                    ⚠
                  </span>
                  <span className="sr-only">Risk flag: </span>
                  {flag}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Two Column Layout */}
        <div className="grid grid-cols-1 divide-y sm:grid-cols-2 sm:divide-x sm:divide-y-0 sm:divide-slate-100">
          {/* Vitals to Check */}
          <div className="p-5">
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
              Vitals to Check
            </h3>
            <ul className="space-y-1.5">
              {brief.vitalsToCheck.map((vital) => (
                <li key={vital} className="flex items-center gap-2 text-sm text-slate-700">
                  <svg
                    aria-hidden="true"
                    className="text-jeevandata-500 h-3.5 w-3.5 flex-shrink-0"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                  </svg>
                  {vital}
                </li>
              ))}
            </ul>
          </div>

          {/* ICD-10 Hints */}
          <div className="p-5">
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
              ICD-10 Hints
            </h3>
            <ul className="space-y-1.5">
              {brief.icd10Hints.map((hint) => (
                <li key={hint} className="flex items-center gap-2 text-sm text-slate-700">
                  <svg
                    aria-hidden="true"
                    className="h-3.5 w-3.5 flex-shrink-0 text-violet-500"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z"
                    />
                  </svg>
                  {hint}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Medications Note */}
        <div className="border-t border-slate-100 p-5">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Medications Note
          </h3>
          <p className="text-sm text-slate-700">{brief.medicationsNote}</p>
        </div>

        {/* Suggested Followups */}
        {brief.suggestedFollowups.length > 0 && (
          <div className="border-t border-slate-100 bg-slate-50 p-5">
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
              Suggested Follow-ups for Doctor
            </h3>
            <ul className="space-y-2">
              {brief.suggestedFollowups.map((followup) => (
                <li key={followup} className="flex items-start gap-2 text-sm text-slate-700">
                  <span
                    aria-hidden="true"
                    className="bg-jeevandata-100 text-jeevandata-600 mt-1 flex h-4 w-4 flex-shrink-0 items-center justify-center rounded-full text-[10px] font-bold"
                  >
                    ?
                  </span>
                  {followup}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button className="bg-jeevandata-500 hover:bg-jeevandata-600 flex flex-1 items-center justify-center rounded-lg px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-all active:scale-[0.98]">
          Mark as Reviewed
        </button>
        <button className="flex items-center justify-center rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50">
          <svg
            className="mr-2 h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M6.72 14.25l4.46-4.46c.48-.48.48-1.26 0-1.74L9.35 5.36a1.22 1.22 0 00-1.74 0l-4.46 4.46c-.48.48-.48 1.26 0 1.74l1.83 1.83m7.27-5.49L17.7 7.21a1.5 1.5 0 012.12 0l1.5 1.5a1.5 1.5 0 010 2.12l-5.35 5.36-3.18 1.06 1.06-3.18 5.35-5.36z"
            />
          </svg>
          Edit
        </button>
        <button className="flex items-center justify-center rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50">
          <svg
            className="mr-2 h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
            />
          </svg>
          Export
        </button>
      </div>
    </div>
  );
}
